### ISSUE TITLE
Is strongtypes safe to depend on?

### ISSUE THREAD

**Issue by JakobDev** [FelixTheC/strongtyping#113]
I'm planning to use strongtypes in a upcoming project, which is a library.  The [PyPi page of strongtypes](https://pypi.org/project/strongtyping) shows this:

> This is the release for Python-3.10 only
> 
>     If you need a different version please checkout the release Tags 2.*.*

This rises the question: How safe is it, to depend on strongtypes? My lib will require Python 3.10, but for the future, it will be bad if my lib depends on this and a new Version, which only works with 3.11 will be uploaded. Telling Users of my lib to install from GitHub if they want older versions, is not a good practice.

**Comment by FelixTheC** [comment]
@JakobDev could I answer your question?? If you need any more help I'm here.
