### ISSUE TITLE
Infinite recursion when @dataclass decorator comes after @match_class_typing

### ISSUE THREAD

**Issue by froody** [FelixTheC/strongtyping#115]
**Describe the bug**
As per the [documentation](https://strongtyping.readthedocs.io/en/latest/match_class_typing/), the `@dataclass` decorator should appear after `@match_class_typing`, e.g.

```
@match_class_typing
@dataclass
class Dummy:
    attr_a: int
    attr_b: str
```

If you add a method and call it, like so:
```
@match_class_typing
@dataclass
class MyType:
    value: float = None

    def method(self):
        pass

req = MyType()
req.method()
```
then I get infinite recursion:

```
Traceback (most recent call last):
  File ".../wat.py", in <module>
    req.method()
  File ".../python3.10/site-packages/strongtyping/strong_typing.py", line 59, in inner
    cached_key = (func, args.__str__(), kwargs.__str__())
  File ".../python3.10/site-packages/strongtyping/strong_typing.py", line 59, in inner
    cached_key = (func, args.__str__(), kwargs.__str__())
  File ".../python3.10/site-packages/strongtyping/strong_typing.py", line 59, in inner
    cached_key = (func, args.__str__(), kwargs.__str__())
  [Previous line repeated 330 more times]
RecursionError: maximum recursion depth exceeded
```

Reversing the order of decorators, i.e.

```
@dataclass
@match_class_typing
class MyType:
    value: float = None

    def method(self):
        pass

req = MyType(7)
```
will fix the infinite recursion but break strongtyping (i.e. the example above doesn't throw an exception when an int is passed where a float is expected.

I was able to work around this by adding `__repr__` to the list of skipped methods in `strong_typing.py` (i.e. in addition to `__init__`) but I'm not sure if that's the right fix.

**Python Version used**
Python 3.10.8

**Package Version used**
strongtyping 3.10.6

**Addon in use**
strongtyping_modules [yes/no]

**To Reproduce**
```
@match_class_typing
@dataclass
class MyType:
    value: float = None

    def method(self):
        pass

req = MyType()
req.method()
```
**Expected behavior**
Code runs an prints nothing

**Comment by FelixTheC** [comment]
thx for using my package, at the first sign it looks like that it has something to do with `__repr__` I will Debug it more deeply to find the why.

**Comment by FelixTheC** [comment]
I found the reason the problem is this line
`cached_key = (func, args.__str__(), kwargs.__str__())`
I will add fix during this day I expect a release this afternoon

**Comment by froody** [comment]
Thanks for fixing it so quickly!
