### ISSUE TITLE
Are there errors for undefined keys?

### ISSUE THREAD

**Issue by yupix** [FelixTheC/strongtyping#129]
First of all, thank you for creating such a useful library.

Is it possible to return an exception for undefined keys?
As an example, if I pass a dict to `User` with a key `age` that I have not defined, it will return an exception.

The reason I want this feature is to help find things that are not defined in the TypedDict. It would be nice to be able to log warnings, etc. even if they are not exceptions.

```python
from typing import TypedDict

from strongtyping.strong_typing import match_class_typing

@match_class_typing
class User(TypedDict):.
    id: str
    username: str
    description: str | None

User({"id": "0123", "username": "test", "description": None, "age": 10})
```

Due to my inexperience with English, I am using DeepL. I apologize if you find anything offensive.

**Comment by FelixTheC** [comment]
Could you please tell me which Python version you're using? 
I plan to put this feature in the latest version which requires Python 3.12.

I will then extend the decorator to support
`throw_on_undefined`

this will be the TestCase:
```python
def test_undefined_keys_raise_error():

    @match_class_typing(throw_on_undefined=True)
    class User(TypedDict):
        id: str
        username: str
        description: str | None
    
    with pytest.raises(UndefinedKey):
        User({"id": "0123", "username": "test", "description": None, "age": 10})
    
    assert User({"id": "0123", "username": "test", "description": None})

```

**Comment by FelixTheC** [comment]
feature is now available at https://pypi.org/project/strongtyping/3.12.1/
