### ISSUE TITLE
Question: What is difference between strongtyping and typeguard?

### ISSUE THREAD

**Issue by eggplants** [FelixTheC/strongtyping#84]
Interesting project! But this project resembles [agronholm/typeguard](https://github.com/agronholm/typeguard). Please tell what is difference and stronger point than typeguard.

I think this project has more modern dev environment and reports mismatched type as `TypeMisMatch`, unlike typeguard's `TypeError`. So in other points?

**Comment by FelixTheC** [comment]
What I can tell for the Moment is that I Support different levels (severity_level) of handling type missmatches.
For example you can disable the typechecking without removing the decorator.

- caching for better performance.
- an alternative to `@property` with `getter_setter` or `setter` and `getter`
- real typed Namedtuple.
- decorators which adds type informations to the docstring automatically. 
-  an own type `Validator[<type>, <function>]`. 

And I allready have a working solution for the PEP-563.
Besides this I also created a separate project which uses Cython for a better performance especially for lists and dicts.

But typeguard has some other Features which I don't have like this pytest addon and more. And there are more people involved.

I hope this answers your question a little bit.

**Comment by eggplants** [comment]
Thank you for your helpful answer!
