### ISSUE TITLE
duck type compatability

### ISSUE THREAD

**Issue by hjalmarlucius** [FelixTheC/strongtyping#93]
It would be great if there were a switch to allow duck type compatability - e.g. ints pass float checks. This would make the type checking consistent with mypy and mypyc. I would think the easiest solution would be to replace `float->Real` and `int->Integral` in checks.
https://mypy.readthedocs.io/en/stable/duck_type_compatibility.html

**Comment by hjalmarlucius** [comment]
This function seems to work:
```py
from numbers import Integral
from typing import get_origin
from typing import get_args

def replace_type(structure: Any, fromtype: type, totype: type) -> Any:
    if structure is fromtype:
        return totype
    if (origin := get_origin(structure)) is fromtype:
        structure.__origin__ = totype
    oldargs = get_args(structure)
    newargs = tuple(replace_type(arg, fromtype, totype) for arg in oldargs)
    if origin is not None and oldargs != newargs:
        return origin[newargs]
    return structure

# example
replace_type(dict[str, int], int, Integral)
```

**Comment by FelixTheC** [comment]
what about this??
`
from numbers import Integral, Real
Number = Union[Integral, Real]


@match_typing
def adder(x: int, y: Number):
    return x + y
`

**Comment by FelixTheC** [comment]
Will your issue be solved with the following solution https://github.com/FelixTheC/strongtyping/blob/93-duck-type-compatability/docs/match_typing.md#allow-duck_typing??

**Comment by hjalmarlucius** [comment]
No, my point was that mypy checks some things differently than python's `isinstance` check - the below is ok according to mypy because it follows the numbers hierarchy but not at runtime as `int` is not a subclass of `float`.

```
x: float = 3
assert isinstance(x, float)
```

**Comment by FelixTheC** [comment]
These are the tests according to your Initial comment https://github.com/FelixTheC/strongtyping/blob/93-duck-type-compatability/strongtyping/tests/test_duck_typing.py

**Comment by FelixTheC** [comment]
Please feel free to create some too which I can add

**Comment by hjalmarlucius** [comment]
That looks like a very good implementation, thanks!

**Comment by FelixTheC** [comment]
Ok then I will create a new release with this include.
